### ISSUE TITLE
Alexnet Convolution layer filter size different. 

### ISSUE THREAD

**Issue by imranicp** [arashno/tensorflow_multigpu_imagenet#10]
the number of filters in the convolution layers in alexnet are different, 64 instead of 96 in first layer and 196 instead of 256 in 2nd convolution layer. is there any particular reason for this?

**Comment by arashno** [comment]
Some implementations (like https://github.com/soumith/imagenet-multiGPU.torch) use 64 and 192.
No much difference in performance.
