### ISSUE TITLE
Cannot evaluate on DenseNet

### ISSUE THREAD

**Issue by huiofficial** [arashno/tensorflow_multigpu_imagenet#12]
when I try to run eval.py, I got this problem: 

`python eval.py --num_threads 8 --architecture densenet --log_dir densenet_Run-31-07-2018_12-45-51/ --path_prefix /root/ImageNet/val/ --data_info val.txt`

> Namespace(architecture='densenet', batch_size=512, crop_size=[224, 224], data_info='val.txt', delimiter=' ', depth=50, load_size=[256, 256], log_dir='densenet_Run-31-07-2018_12-45-51/', num_batches=98, num_channels=3, num_classes=1000, num_samples=50000, num_threads=8, path_prefix='/root/ImageNet/val/', save_predictions=None, top_n=5)
> Filling queue with 2000 images before starting to train. This may take some times.
> Traceback (most recent call last):
>   File "eval.py", line 134, in <module>
>     main()
>   File "eval.py", line 130, in main
>     evaluate(args)
>   File "eval.py", line 33, in evaluate
>     logits = arch.get_model(images, 0.0, False, args)
>   File "/root/ImageNet/repositories/tensorflow_multigpu_imagenet/arch.py", line 15, in get_model
>     return architectures.densenet.inference(inputs, args.depth, args.num_classes, wd, is_training, transferMode)
>   File "/root/ImageNet/repositories/tensorflow_multigpu_imagenet/architectures/densenet.py", line 21, in inference
>     return getModel(x, num_output, K, stages, wd, is_training, transfer_mode= transfer_mode)
>   File "/root/ImageNet/repositories/tensorflow_multigpu_imagenet/architectures/densenet.py", line 60, in getModel
>     x = block(x, stages[0], K, is_training= is_training,  wd= wd)
> IndexError: list index out of range
> 

How to solve this?

**Comment by arashno** [comment]
What depth did you use for training?
I believe you need to provide the same depth argument for the eval.py as well.

**Comment by huiofficial** [comment]
thank you very much! depth is the problem. sorry for bothering you.
