### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by jianghuairong** [arashno/tensorflow_multigpu_imagenet#3]
when I run imagenet, and when it comes to epoch 2 , step 16000 , the pycharm stop and say Process finished with exit code 139 (interrupted by signal 11: SIGSEGV) ,Could you please tell me what's the matter?

**Comment by arashno** [comment]
Please provide more information:
1- Your OS
2- Your TF version
3- How much memory you have
4- Did it happen one time or it happens every time?

**Comment by jianghuairong** [comment]
1. Ubuntu 16.04.3 
2. tensorflow 1.4
3. 12g TITAN Xp
4. I run twice,it always happens

**Comment by arashno** [comment]
I have never encountered this before.
The error code indicates a segmentation fault. 
Do you know how much memory does it use just before the crash?

**Comment by jianghuairong** [comment]
I do not know，do you mean the memory maybe not enough ?

**Comment by arashno** [comment]
Yes,
I usually run my experiments with over 15GB of memory.

**Comment by jianghuairong** [comment]
I use batch_szie 64, and when Process  stop,its speed becomes 4 sec/batch(usually 1 sec/batch)

**Comment by arashno** [comment]
You can try decreasing the size of the input pipeline cache.
In data_loader.py line 66, change 5000 to 500.
This might slow done reading images from disk a little bit but it will consume less memory.

**Comment by jianghuairong** [comment]
thanks，i will try

**Comment by zhuzilin123** [comment]
I'm a novice, I'm looking at your code, but I don't know how to run through your code completely (such as which folders need to be built, how to place data sets). If possible, could you tell me something about it?
