### ISSUE TITLE
Dense Layers

### ISSUE THREAD

**Issue by a2018c** [arashno/tensorflow_multigpu_imagenet#4]
This is a discussion more than reporting bug

In training DenseNet Model:
Q1) there is a parameter --depth, if  it is set to  "--depth 201",  does it also mean it will have 201 layers? 
      if depth=201, stages= [6, 12, 48, 32], what is the relationship between layers and stages?

Q2) from the densenet.py, 
    stages= []
    K=32
    if depth == 121:
      stages= [6, 12, 24, 16]
    elif depth == 169:
      stages= [6, 12, 32, 32]
    elif depth == 201:
      stages= [6, 12, 48, 32]
    elif depth == 161:
      stages= [6, 12, 36, 24]
      K= 48
any idea why only when depth=161 k is set to 48 and others use k=32? 

Q3) Does k mean growth rate?

Q4) from "python train.py --help"
  --depth DEPTH         The depth of ResNet architecture
Can -depth be applied to DenseNet architecture too?

Look forward to hearing from you, thanks!

**Comment by arashno** [comment]
Q1) Yes, --depth means the number of layers. Each stage means a 1x1 conv layer followed by another 3x3 conv layer. Therefore, stages equal to 6 means 6 stages in a sequence. Please refer to table 1 of the DenseNet paper for details.

Q2 & Q3) Yes, K is the growth rate. This implementation is based on an older version of the paper (v3) in which the authors used K=48 for their 161-layers model.

Q4) Yeah it also applies to the DenseNet. I need to fix the comment.
Thanks for noticing that.

**Comment by a2018c** [comment]
Thanks for your reply!

**Comment by a2018c** [comment]
There is architectures/googlenet.py, it is Inception? if yes, is it v2 or v3 or v4?

Look forward to hearing from you, thanks!

**Comment by arashno** [comment]
It is an implementation of this paper:
https://arxiv.org/pdf/1409.4842.pdf
