### ISSUE TITLE
Using vgg or googlenet results in Value Error

### ISSUE THREAD

**Issue by imranicp** [arashno/tensorflow_multigpu_imagenet#7]
I am trying to train with googlenet and vgg, alexnet and resnet training works. i am training on imagenet data, with 2 classes. the scripts fails here, 
top1acc = tf.reduce_mean(
                tf.cast(tf.nn.in_top_k(logits, labels, 1), tf.float32)).
the error.
ValueError: Tried to convert 'predictions' to a tensor and failed. Error: None values not supported.
upon inspection the logits in case of vgg or googlenet is none.

**Comment by arashno** [comment]
Have you set all the arguments right? I mean have you set --num_classes 2 ?
It is hard to say anything from the error. 
Does this happen for every batch (starting from the first batch) or just some of them?
If it just happens for some of them, does this happen for a particular input image?

**Comment by imranicp** [comment]
Yes i tried with with --num_classes argument, still the same. it happens as soon as the script hits the line described above. starting from the initial batch, i am new to tensorflow and ML, dont know how to investigate further, but the problem occurs in logits, while using googlenet or vgg the logits happens to be empty/none.

**Comment by arashno** [comment]
Have you changed anything in the code?
If you didn't, since you said you are working on the ImageNet dataset,  must be able to reproduce the problem by only having your --data_info file.
Can you share your input file for further investigation?

**Comment by imranicp** [comment]
I found out what the problem was apparently the variable coming from args.model was none, catching else statement, its working now. Thank you.
